language: node_js
node_js:
  - "12"

install:
  - npm install
script:
  - echo 1

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "12"
      script: echo "Deploying to npm"
      deploy:
        provider: npm
        edge: true
        email: "$NPM_EMAIL"
        api_key: "$NPM_AUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true
